build:
  version: "1.0"

product:
  message: "Hey, welcome to Panorama Shop related dev APIs"
  contactDetails:
    name: "Oleksa Panchuk - Product Owner"
    email: "{cipher}f83ac5a34ba5f4657ae8e863c063c1b69efb4d23d0c431eb134f8d1b3ed0823dee0a4b627d091455b4c6600353a3682c"
  onCallSupport:
    - (453) 392-4829